### ISSUE TITLE
Simply doesn't work!

### ISSUE THREAD

**Issue by WrongBit** [manuman94/ytCropper#1]
I pasted URL into field, then press "Crop!" (what is stupid, because I do not crop, I just point program to my source!). Then video loaded into preview, but... I see no any "blue squares" to adjust time! OK, skip this stupid error, I try to enter time manually. But when I did it and confirmed "not robot", page just redirects back to original page with error "invalid URL" - WHAT?? I paste valid URL, it's your script generates hell knows what.

**Comment by manuman94** [comment]
First of all, you are raising an issue in the Github repository of the ytCropper javascript library. This is not the place to ask for support about the web application https://ytcropper.com.

Plus, I NO longer own the application, this library and the website is property of [10BestDesign](https://www.10bestdesign.com/). For any further request ask their support team.

But let me tell you that raising issues calling a free tool "stupid" for not knowing how to use it says a lot of yourself. It is a free tool, provided to the community. Show more respect for developers that help you selflessly.

Greetings.

**Comment by WrongBit** [comment]
Ah... OK! Infantile boys never heard of their work that it's "stupid". Welcome to the adult world! And believe me, there is TONS of stupid software, which doesn't work. Your is one of 'em. I didn't use library as developer - I visited website and library doesn't work - enough said to count library as rubbish.

**Comment by ychaouche** [comment]
@WrongBit keep in mind the website exists since around 2014 and was working correctly, much better than many other websites with same purpose. I believe it is not maintained anymore, and you can look from the log history that commits ended 7 years ago. 

Also, maybe carefully choosing your words would be in your best benefit. Don't expect respect if you don't show some.
